import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          ink: "var(--brand-ink)",
          canvas: "var(--brand-canvas)",
        },
        blue: {
          50: "var(--blue-50)",
          100: "var(--blue-100)",
          200: "var(--blue-200)",
          300: "var(--blue-300)",
          400: "var(--blue-400)",
          500: "var(--blue-500)",
          600: "var(--blue-600)",
          700: "var(--blue-700)",
          800: "var(--blue-800)",
          900: "var(--blue-900)",
        },
        neutral: {
          0: "var(--neutral-0)",
          50: "var(--neutral-50)",
          100: "var(--neutral-100)",
          200: "var(--neutral-200)",
          300: "var(--neutral-300)",
          400: "var(--neutral-400)",
          500: "var(--neutral-500)",
          600: "var(--neutral-600)",
          700: "var(--neutral-700)",
          800: "var(--neutral-800)",
          900: "var(--neutral-900)",
        },
        bg: {
          page: "var(--bg-page)",
          surface: "var(--bg-surface)",
          muted: "var(--bg-muted)",
          hover: "var(--bg-hover)",
          accent: "var(--bg-accent)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          tertiary: "var(--text-tertiary)",
        },
        action: {
          primary: "var(--action-primary)",
          "primary-hover": "var(--action-primary-hover)",
        },
        border: {
          default: "var(--border-default)",
          strong: "var(--border-strong)",
        },
      },
      fontFamily: {
        brand: ["var(--font-brand)", "sans-serif"],
        body: ["var(--font-body)", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      fontSize: {
        11: ["11px", { lineHeight: "1.45" }],
        12: ["12px", { lineHeight: "1.5" }],
        13: ["13px", { lineHeight: "1.5" }],
        14: ["14px", { lineHeight: "1.5" }],
        15: ["15px", { lineHeight: "1.5" }],
        16: ["16px", { lineHeight: "1.5" }],
        17: ["17px", { lineHeight: "1.5" }],
        22: ["22px", { lineHeight: "1.3" }],
        28: ["28px", { lineHeight: "1.25" }],
        36: ["36px", { lineHeight: "1.2" }],
      },
      spacing: {
        0: "0px",
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        10: "40px",
        12: "48px",
        16: "64px",
        20: "80px",
        24: "96px",
      },
      borderRadius: {
        xs: "2px",
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "20px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
