import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          ink: "var(--brand-ink)",
          canvas: "var(--brand-canvas)",
        },
        blue: {
          50: "var(--blue-50)",
          100: "var(--blue-100)",
          200: "var(--blue-200)",
          300: "var(--blue-300)",
          400: "var(--blue-400)",
          500: "var(--blue-500)",
          600: "var(--blue-600)",
          700: "var(--blue-700)",
          800: "var(--blue-800)",
          900: "var(--blue-900)",
        },
        green: {
          50: "var(--green-50)",
          100: "var(--green-100)",
          200: "var(--green-200)",
          300: "var(--green-300)",
          400: "var(--green-400)",
          500: "var(--green-500)",
          600: "var(--green-600)",
          700: "var(--green-700)",
          800: "var(--green-800)",
          900: "var(--green-900)",
        },
        red: {
          50: "var(--red-50)",
          100: "var(--red-100)",
          200: "var(--red-200)",
          300: "var(--red-300)",
          400: "var(--red-400)",
          500: "var(--red-500)",
          600: "var(--red-600)",
          700: "var(--red-700)",
          800: "var(--red-800)",
          900: "var(--red-900)",
        },
        amber: {
          50: "var(--amber-50)",
          100: "var(--amber-100)",
          200: "var(--amber-200)",
          300: "var(--amber-300)",
          400: "var(--amber-400)",
          500: "var(--amber-500)",
          600: "var(--amber-600)",
          700: "var(--amber-700)",
          800: "var(--amber-800)",
          900: "var(--amber-900)",
        },
        orange: {
          50: "var(--orange-50)",
          100: "var(--orange-100)",
          200: "var(--orange-200)",
          300: "var(--orange-300)",
          400: "var(--orange-400)",
          500: "var(--orange-500)",
          600: "var(--orange-600)",
          700: "var(--orange-700)",
          800: "var(--orange-800)",
        },
        neutral: {
          0: "var(--neutral-0)",
          50: "var(--neutral-50)",
          100: "var(--neutral-100)",
          200: "var(--neutral-200)",
          300: "var(--neutral-300)",
          400: "var(--neutral-400)",
          500: "var(--neutral-500)",
          600: "var(--neutral-600)",
          700: "var(--neutral-700)",
          800: "var(--neutral-800)",
          900: "var(--neutral-900)",
        },
        bg: {
          page: "var(--bg-page)",
          surface: "var(--bg-surface)",
          muted: "var(--bg-muted)",
          hover: "var(--bg-hover)",
          active: "var(--bg-active)",
          accent: "var(--bg-accent)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          tertiary: "var(--text-tertiary)",
          accent: "var(--text-accent)",
          disabled: "var(--text-disabled)",
          "on-dark": "var(--text-on-dark)",
        },
        action: {
          primary: "var(--action-primary)",
          "primary-hover": "var(--action-primary-hover)",
          "primary-active": "var(--action-primary-active)",
          secondary: "var(--action-secondary)",
          "secondary-hover": "var(--action-secondary-hover)",
          danger: "var(--action-danger)",
          "danger-hover": "var(--action-danger-hover)",
          success: "var(--action-success)",
          "success-hover": "var(--action-success-hover)",
        },
        border: {
          default: "var(--border-default)",
          strong: "var(--border-strong)",
          focus: "var(--border-focus)",
        },
        status: {
          "error-base": "var(--status-error-base)",
          "error-strong": "var(--status-error-strong)",
          "error-tint": "var(--status-error-tint)",
          "info-base": "var(--status-info-base)",
          "info-strong": "var(--status-info-strong)",
          "info-tint": "var(--status-info-tint)",
          "success-base": "var(--status-success-base)",
          "success-strong": "var(--status-success-strong)",
          "success-tint": "var(--status-success-tint)",
          "warning-base": "var(--status-warning-base)",
          "warning-strong": "var(--status-warning-strong)",
          "warning-tint": "var(--status-warning-tint)",
        },
      },
      fontFamily: {
        brand: ["var(--font-brand)", "sans-serif"],
        body: ["var(--font-body)", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      fontSize: {
        11: ["11px", { lineHeight: "1.45" }],
        12: ["12px", { lineHeight: "1.5" }],
        13: ["13px", { lineHeight: "1.5" }],
        14: ["14px", { lineHeight: "1.5" }],
        15: ["15px", { lineHeight: "1.5" }],
        16: ["16px", { lineHeight: "1.5" }],
        17: ["17px", { lineHeight: "1.5" }],
        22: ["22px", { lineHeight: "1.3" }],
        28: ["28px", { lineHeight: "1.25" }],
        36: ["36px", { lineHeight: "1.2" }],
      },
      spacing: {
        0: "0px",
        px: "1px",
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        10: "40px",
        12: "48px",
        16: "64px",
        20: "80px",
        24: "96px",
      },
      borderRadius: {
        xs: "2px",
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "20px",
        "3xl": "24px",
        full: "9999px",
      },
      screens: {
        mobile: { max: "767px" },
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
      },
    },
  },
  plugins: [],
};
export default config;
